"""try2

Revision ID: 1d3f6811ab27
Revises: ef150fa3e89b
Create Date: 2023-12-11 20:36:46.621798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3f6811ab27'
down_revision: Union[str, None] = 'ef150fa3e89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_char', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('group_char')
    )
    op.create_table('lectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('group_char', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['group_char'], ['groups.group_char'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=True),
    sa.Column('lectors_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lectors_id'], ['lectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_marks')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('lectors')
    op.drop_table('groups')
    # ### end Alembic commands ###
